baseurl = "https://benjamin-altpeter.de"
languageCode = "en"
title = "Benjamin Altpeter"
disableKinds = ["taxonomy", "taxonomyTerm"]
canonifyURLs = true
PygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true
pygmentsUseClasses = true
rssLimit = 10

[permalinks]
    post = "/:slug/"

[markup.goldmark.renderer]
    unsafe = true
