baseurl = "https://benjamin-altpeter.de"
languageCode = "de-de"
title = "Benjamin Altpeter"
disableKinds = ["taxonomy", "taxonomyTerm"]
canonifyURLs = true
PygmentsCodeFences = true
pygmentsstyle = "default"
pygmentsCodeFencesGuessSyntax = true

[permalinks]
    post = "/:title/"
